name: Check code format

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp' ]

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - '.'

    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: 13
          check-path: ${{ matrix.path }}
